### ISSUE TITLE
Serviço Docker não estabilizando, 

### ISSUE THREAD

**Issue by MarcelFernandesCGEO** [HumbertoDiego/django-cbers4amanager#5]
Versão Docker: Docker Windows 20.10.17, Build 100c701

Após realizar o docker-compose up -d, não é possível realizar o próximo passo, tendo em vista que o serviço fica reinicializando.

Uma das resoluções adotadas foi no Dockerfile, remover o comentário da última linha:
CMD ["python", "manage.py","runserver","0.0.0.0:81"]
E adicionar, no my_wrapper_script.sh uma linha inicial com:
python manage.py makemigrations && python manage.py migrate

**Comment by HumbertoDiego** [comment]
Implementado. obrigado pela solução.
